[[Kokkos]]
arch = "aarch64"
git-tree-sha1 = "861050a682cee9b02a1d12e391d8c389856f8f7c"
os = "macos"

    [[Kokkos.download]]
    sha256 = "73a48c171918f69fb1edacd26e860e011bcac6863c52859e523c176645540ff2"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.aarch64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bc86236e86b712521d396e1990ee058b6bb676b"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "67c902642d1d572a190f5665da3c8cd8432c1974d303dad58f8ab9fbe8041ef0"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce754dbbf20400f1929ae9b7841ef872bb81cb87"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "edf0dabb2bc965ee7cf8d5d92bb81c936d5d166084964c7aff69652c938fb480"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d440239ef75cc6fc93a45e9fc27d6937f94a1153"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "8dc580ff8e1bce8864209c10aadbef998424ea4e105665aab3805eb4fdeb6c1d"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ad4628183abcdbae607532c7961dde0042cdf0e"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "74a51ed1bc21f43f2981e79f8a0bbb4e93581097ccadb8cc9b538a071034f8d8"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e34931196f3b36e4ae56259df5e132948236c7ca"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "b53ce7792548f5541cb90cb2a458fef6550cd99e6916a4fc8db3f2fd153ffd2c"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c9e9646ff76949b091ab3ca7366c846060db429"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "532f62a3684018025afbbff2b1233d62947210d042408af01ecdc298357aaefa"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "2665477166e9a658dca032df1a663a860c0eb4de"
os = "macos"

    [[Kokkos.download]]
    sha256 = "54b96122a8038534010967ca0b421eb8a70d324ffbf02e89a81180b7f15f5628"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "faf4b24fdfc6af1abc5243d3a56b659d02244298"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "283096c24fdf303c4afff7b4178f900f62d78edfb2ed17c37d0a62a39eae794c"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d95425478c8dd7810300c9ce4a3bdf5523254884"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "bfe0efe049044ff243738a1741c708aca99adcce49978c1565a8b03283d4f1bf"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad531c7130556e20f389530a5f13990dbee4515c"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "9b512d1df94673afc8947558c135e2a4ddcc904d9fbbe46830b4080fb6629a2f"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ec06f64bc57b55719113e9a9fe3073f866ad25a"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "4221ab9d1e0d3647853508fba0e2ae5d43fa64a845dc86d10734fe6940940c01"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "14848306e35b89f819c051ba3c8af938da7079ec"
os = "freebsd"

    [[Kokkos.download]]
    sha256 = "4bc738b22018f687dd45091a3f628df7bef1027e2ae159a667ef3e235fe21c62"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-unknown-freebsd.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3af7b5b4f03dabba9d3804a058f22d0fed1d8391"
os = "windows"

    [[Kokkos.download]]
    sha256 = "a85d5689e955f43c202e51bb7cc947eca9103d384add93a1e575d0bb9e64b6e0"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b072f4d112a410d3ee93ed35265d159eac390224"
os = "windows"

    [[Kokkos.download]]
    sha256 = "6698fcaa264716f3a39a4b5884540765198713cc0956b67721c8654d41bd7322"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.1.0+1/Kokkos.v4.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
