[[Kokkos]]
arch = "aarch64"
git-tree-sha1 = "b17777cf1b1c8e4168ca4cd26316de1fa4595b87"
os = "macos"

    [[Kokkos.download]]
    sha256 = "df321e6e9e35be958138a15d69cdfd7ff9bffbe4997564452e3efdb5a9ccca9c"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.aarch64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb204ce5649fa05c1d093ba6a61b425beb82e58a"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "a26298ff86005af2f1694f7610d9ea1d677738d24b138477fb3ecf9a5c1c9df9"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d7961a96cf1bb0d3744648d71df0f3a27ac372b"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "1d8a369e666d58f233351e8dd703e3ed3bb74067487c72cbc943cf453589b6ce"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "393c67d9b42e6a27668a3ddc99d281e6cf67aba2"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "5a0bec18d760c05689773d1dafde473fb6a4ac6f3a3de552dbc7e9df32f8b4fe"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f1d7672dba8e3e3a7b80a901c696a1174c9bfd7"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "db30e38c2ca42c1bb728477bd294b87c6b949ac7ad03d508aab3f06a1524bd40"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c6ebdc5720d73798de6200dd41ca2b19cad5eb7"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "68eee6fb8590594732801bc71a3702c137c892685f1f59f00c5557b12b4dec4a"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c14b47dd7403cb96aa0f004ab0d1c82e76d2cd5"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "4a49801e58f9c1096d418f9fdb123bb26ee256ecbb0177e7e4beca7917847d2d"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "62fe96f72ff5abcfe8949527a15c9d73eeaf940b"
os = "macos"

    [[Kokkos.download]]
    sha256 = "5d0b0e62d287bc4535cc8ab63b51cfc499251b4aa46081c3bdc8198598973629"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eab2b8a08e5eb052b454a085f8d9ae032c15b0ca"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "19f815a201a88f5204cf60ea81442b77c2477ceef27273c5d342576877769c8f"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "208fe108d01302aca40669e98a9c317e02b7ffa7"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "0ef829d428554420edc5288096e7d55e43ddcbc7ae236271f3ed1bb6f0cb8183"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd68cab47c659dd3ffcc142b6a52d8422c2e304b"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "b68447b706d5c9f3a7de0504fae7bbebdb5468c0edebbe8b7305884070ce92cb"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c854b88e6ecf2f61b6704c5db658a8e47b6f5e89"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "43bb34aa6853f486c1031ccad1d5dad4c481dd2244ee398e1c1f89d845482846"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "c39784babccb7df91584d049d86f74740b8bb34d"
os = "freebsd"

    [[Kokkos.download]]
    sha256 = "e35b0380fc2b5d5205223eb2e5c3111437e10f078c2e5ba57922828fc3d8cb6d"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-unknown-freebsd.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f8122652463c47fcd512012d3376e0757eee8f0"
os = "windows"

    [[Kokkos.download]]
    sha256 = "2ec147b1b8b3f35da63dc922b56d24d949eb67f474953b2e90529a34bfdf3bc8"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48413600d81ce7fce016c7249871faf0083d6861"
os = "windows"

    [[Kokkos.download]]
    sha256 = "77aadf8cd0c20c719dbe23c2606193721e8294fc5fa8608db0412499856f60e6"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.2.0+0/Kokkos.v4.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
