[[Kokkos]]
arch = "aarch64"
git-tree-sha1 = "e937a710d07598ee7a86a615d2b9b13faa2b3fcd"
os = "macos"

    [[Kokkos.download]]
    sha256 = "e049c073fa0e6e3fdda3e4a51715cc40cf0761eaec688908f96d78b92ee40f9d"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.aarch64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f51b380b8c70797bfd7b751b8ea6360acc35ee64"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "84b473e34f5ffc7e03f2eb6af859438266ad617e57392d6030d783267a8f7408"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f579cb15b299b82b98f947278c89fbd75751844"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "4c0c261c860c6cdb80f738f83f156ba25accc27ff47095e61251ff8d1300f7e6"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "576459ed947041ee72c5cbc2b40252145461485a"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "795fd94c5de01a294dc48e29953d30ad49fa2d4ae07d8fdd8a2b857992f6c529"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f3e876115a77f0af6b2445651986a76d2aeca0d"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "2f9e5baa3d612a386304aa2cbc26eb8d41c9edd4ddbf01aad0f604096759e9c2"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e562cc0800cb15cd260439b9895a722a72424d"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "bbbc9c905c0e65d710e31107af271f4d21810e44f28c2d067965ab690dcbd8d1"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f58c09b2217f59ebc3d2fd3fe7f10666e2a2fde"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "343f57a36c2e5c44d0d426bae6acc9f041555c4c8a696d3afa01b4e8702a39ef"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "c6d864249dc9ce00a3ea7837b787d41046f005f0"
os = "macos"

    [[Kokkos.download]]
    sha256 = "15d5f8a0255076022054cad5e04effb356a95300f45294029e592c138d35b92b"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aae25cc147e160baf6b24f8548bf4374ce4e0d4c"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "f90d4496c906cf868340633c36b45be553ced3856a58e5df2a77fa268297cf1f"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04effe3bec92121ac82baec328e27d0f74d3b323"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "1619deba9ccc1a26039a7a5e2d0eafabd5c82b7118041648668b0714517c4d5e"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cdab3de26d36ae51122328d2ffc03896d298e86"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "674487b05342ecc5f421b22873dfbdd13bfa2015478a4e652080e440fb363def"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "839ac3b9caf1ad8d8564e98dd010e958ea78dd49"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "9128fe54dc29228cda3db8a604c66946bc5e20cd663313c3d2b6f733fd26fdd8"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "94aff2ffa6f0245dbfca50e4e986dd91205cc27f"
os = "freebsd"

    [[Kokkos.download]]
    sha256 = "44b11742b7e1672bb14b1d01cb128b85c1d3c2dec8ead1367d2f0a4ad0f5f738"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-unknown-freebsd.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3ea11ced4b12afaf61aa93f1d1beec7f5bf7df5"
os = "windows"

    [[Kokkos.download]]
    sha256 = "d99339084a753b4f42773c895a03ac502e814a6ca2d6c190f25b0f23666673d5"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3ee1dae22a50492220a2c8c06e17d92f9b080d3"
os = "windows"

    [[Kokkos.download]]
    sha256 = "8d7abf4472955550e0533aa39adc08e3abec0565582a7955d62d250a173baf33"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.0+0/Kokkos.v4.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
