[[Kokkos]]
arch = "aarch64"
git-tree-sha1 = "0b297724df7ef8097d275589656d880a2a93f9b2"
os = "macos"

    [[Kokkos.download]]
    sha256 = "8b5f191990870dfdc70606654db499eb0b8b00a727ef3afdeb767a9667be0f40"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.aarch64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42e2e5316af10a7692d331746a46be343b54eb2c"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "3396378ec15dc2995cf22798257cbfb42035a833db502295223a536cc394dfb3"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5969b1dd66bb26e667c9b45537be0e3fc294419"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "f63ec108b78f5f57b5115692e3f944ff7ae79d7c3fb8a661daf3dc8ce34c1976"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5680977551d456521b167d7f2615fd6de46aace5"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "365aa744ce429b5f0d29e3e92948d79087117a57c86cce865fc70612a55da43c"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36cd09b68bd7c63bb374fee3cd3da80294ead340"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "d66b074a78c3d471b195684c335936efaf9e8cac8b3f2dc6352395b4966fd40e"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "089bd989f8e9974ba350e5f1b929a523161138d9"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "9e2c6d705c969e32452a61a7e00a3d32fee9306d1e48e158cb83a056245b407d"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a32c931026134a656fbfff3cdfe320224a707d4b"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "7398d8e9d52fdf1d1ba4a00b3ab3a78bfc46044ebdcb5d9368ae3f807f4f2851"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "dc2210505a89c96f36e6815d5279fb69c000ca2d"
os = "macos"

    [[Kokkos.download]]
    sha256 = "0352b7dd72d91f7a10ae7b97f74861c4f7aa95d61e39996bf198e398ec403975"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "373774e715130efbfe747f82add9bf3ece7f910f"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "210a2a9d97d494a860398a1333f27ba84481538e5bca7acffd3a6dc1688d6e34"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d54bbd62bdb5e50a3f573788e06fd72fffb51c9e"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "5c71de1b2971e2dc7288a3758219eab097aad1d07d04b52022895a24b9628fc2"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c91e34e55d8cff31056e2d767a58e370b67e079b"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "9bebfa59dfb37d3bdde54572c0f88ed06550aa4495bb125fb8bbbedcfe041194"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e80998c4c603065d3b8541ba7ba39f499e946d5f"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "c378e2ccfcd3a9d52eac1157dff2a2830c1154e3ccf6ab03522780a35945d03d"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "b1ded935ab6fffdfb2f4f8a8f9fab6cc8ffc7024"
os = "freebsd"

    [[Kokkos.download]]
    sha256 = "9428e875057163568dc4e7619b8b7ce76efe807c1629de3ee1ce2d43bf032090"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-unknown-freebsd.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c27569b4eb779e8771241fdcf557e92b31994db"
os = "windows"

    [[Kokkos.download]]
    sha256 = "29c2f1dade6dc6fb8ffe1597a29daa00ac34054adc7a18c3dfc83263e67234f7"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2643a59fec1d4b98f7f4bde03ade4343de181e55"
os = "windows"

    [[Kokkos.download]]
    sha256 = "067c109c7b7f8a16f525424af5671e6951c4e01da78e66b6cee0274baccf009b"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.0+0/Kokkos.v3.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
