[[Kokkos]]
arch = "aarch64"
git-tree-sha1 = "f4c583258885c79e940c4aec0c4aa570771bcdb7"
os = "macos"

    [[Kokkos.download]]
    sha256 = "0029ea2c6c752d636b34f7bad1ed4c1052d6d636c6ddf491dc02d4fa3696809b"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.aarch64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "540cab54a0b11f93f0d3f5c991a117f0eb7a5ced"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "03e26163f2e7e6251011f779bac43053f4155dd05da736e9d36f265715988feb"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31124ef01993a7aa43140805b5373a9bb0ca2325"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "f3d78672f5f4f7dfc62e37d857252f48a80659b3efc05ce67fca7a6ad5dd070e"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f0c049767213ffb55b8b31c7a273259f9decb5d"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "bd40f9471089435fc975a76b4e7cd8a75495967f67f8f6e7893ff750fde82996"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.aarch64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eff40b64dd53afc8523a23cad95566dbf92d085b"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "58532070c45e8e89d18f88c529dafa118e53f6af190f8cfc1ae869602ec31675"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.aarch64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7dabb73a81f0f64d8b831ac043cf74ff6f81ad20"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "694ff75c20bb198c6090d762f14ddbf43c86f9b34897d7dd207cb51442e7ec45"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40f74c3ed32480282a8164b2f519750f48101900"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "282f9b940e446a0f31d87fd923351c3a69f72a91e9e49b8983f90982dbb87c96"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "862ab8206595f0eaf316d53a3944649b4ceaf7df"
os = "macos"

    [[Kokkos.download]]
    sha256 = "7802ce0ea90bf91bb452a678e5b7026fc2184e8289682edefa573bd341e7b6b8"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bc071eb3ae1ce7223d6b3960dec9b54cd7d1868"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "a9772addf5f67a8f086d036812ab1bc63d5d8492c768b30f2766163b1c32e85b"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fe11faab56ae1ea5f930a9f912c1f46465a23cc"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "1c0a3ad3a85ac0530a2520d91c69fdc8d2d356e19ebe9d59b9a4eae8c1620ea9"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b32bb7257802c90fa19e7f37f84a0c3497f466b2"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "0410bb113bf8b29a0e8e8666602da1dfc613a078a65b3cd504b677c4dba079c1"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5c991c0b15a6607337d46b56d18e3b4ea48cd5f"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "73097ce41a7a811d65ca4352d16ed6e542934d76b688739a5ae5ac98af6359fc"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "1efe799c33971fa22f6f8f9c1088676184548640"
os = "freebsd"

    [[Kokkos.download]]
    sha256 = "af8ffb6a3c2163fd7984f70c5f614388201a05c3a428f0a54f34728d3e564897"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-unknown-freebsd.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97ef161a2c62f5f44a260699e81f8a73da57b8ec"
os = "windows"

    [[Kokkos.download]]
    sha256 = "3e67df2890251778610cd1e488d50c7894ee80b882bdcbe862a4d273f1ea2e1c"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0ae2e976072769a6ed35d9c2df98b66e64e6d80"
os = "windows"

    [[Kokkos.download]]
    sha256 = "ed01ad9e974646a1fbf7102cce2f7f8afc030586f306770731a63184e4feea97"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v3.6.1+0/Kokkos.v3.6.1.x86_64-w64-mingw32-cxx11.tar.gz"
