[[Kokkos]]
arch = "aarch64"
git-tree-sha1 = "1061c4675a7b67792e41dba9e10e375ad050c683"
os = "macos"

    [[Kokkos.download]]
    sha256 = "08613c85e7d79129852813500ac34f6cc65f133d9044c300dab7be9aeab8998e"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.aarch64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f0e865cde25dffb7785b608b8184c403c0cf281"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "ecb23e57b737b8fcd9727a025449796e1fa852dfef9b8188540294df154c26ba"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcaa2f083315a765fd6944b4467afd147f222dec"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "d12da88dfff1ba8cfbd9ea5ec939047fb6ae96a8d08e5f3dd68cee53a1eac375"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca2f5a59cff517ed590e1f01f6bdd7bc9c06f75b"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "c474bb7fdd4d8f62821225cd8e4ae8efcff48de2d58cdc6ef72df05aa25625ca"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65805b4dc563a18eafd860906d20945578742c9a"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "7d3d74155818d0738da9f2791f41375e8ea47bf781fec4a462c1ced222b4c478"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ffdc7c9e31a79c06f43ff7b939012442d37b7a1"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "13d6e1fae4fce7b349b9a356e07a0a3a7f438bd1bc9d09c10b362dfbb36d9721"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b195ed3992fdf49dab75aa7b88142639184a5bb6"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "e7af093970f47de1794e72ecf2222d7fa385d468eb1f9229b0a8b38935bcb45a"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "42ddd109c60c004b450900829e2b293429ecdd7e"
os = "macos"

    [[Kokkos.download]]
    sha256 = "1f48a94f064bae0e14ab85c5c971a7a2d6fbcc30f4a9a73fbd3376eb425f0ea9"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-apple-darwin.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9795153c823a1c340022670c3b6136f7e0991489"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "531f006031a2d279f5a67c92586bcc028309601d89208d8bed0205cbd63b637f"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a91cbe3808f59911a1301f9e8b86d031e4c0f1d"
libc = "glibc"
os = "linux"

    [[Kokkos.download]]
    sha256 = "f9dac68c56257d50fac40bf78deeba9fa163d98245880236512d0b673e8ce168"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90277727223fcbf0a81c79a49a4fec9d84affd29"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "12af0a89bc549a564f5fbff88faa276940891b51a7f41c9387f90ba178ce002d"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-linux-musl-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdea4ce5d4cd1225d1a1f1015cb5c838c49fcfc3"
libc = "musl"
os = "linux"

    [[Kokkos.download]]
    sha256 = "7e62fb6c8b8ef229fc98bfe95bfac2fe32ea5d5ab88ce16e1f60230583dd8dca"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-linux-musl-cxx11.tar.gz"
[[Kokkos]]
arch = "x86_64"
git-tree-sha1 = "c6359a8f3f6ad34a4c3b8f28f5b1491c83a06ccc"
os = "freebsd"

    [[Kokkos.download]]
    sha256 = "094ae6431d5236b8c526c8dc97aa7ff462d88a4609b37d261e8ef58251654005"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-unknown-freebsd.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5189192dd14240866b6621c9e29d8a7b7c076432"
os = "windows"

    [[Kokkos.download]]
    sha256 = "4e7badcd53033089b9624e70c1663387441fb95da23a0074724843775f6d9bcf"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Kokkos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cf01479d14606001168c8d68a8d15a14766dadc"
os = "windows"

    [[Kokkos.download]]
    sha256 = "3880063ca6de2a4dcec3d4cc6becf8b1f1c8aca26b302964a3573f5a47933107"
    url = "https://github.com/JuliaBinaryWrappers/Kokkos_jll.jl/releases/download/Kokkos-v4.3.1+0/Kokkos.v4.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
