# Autogenerated wrapper script for Kokkos_jll for aarch64-apple-darwin
export libkokkoscontainers, libkokkoscore

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Kokkos")
JLLWrappers.@declare_library_product(libkokkoscontainers, "@rpath/libkokkoscontainers.3.5.dylib")
JLLWrappers.@declare_library_product(libkokkoscore, "@rpath/libkokkoscore.3.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libkokkoscontainers,
        "lib/libkokkoscontainers.3.5.00.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libkokkoscore,
        "lib/libkokkoscore.3.5.00.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
