# Autogenerated wrapper script for Kokkos_jll for x86_64-apple-darwin
export libkokkoscontainers, libkokkoscore, libkokkossimd

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("Kokkos")
JLLWrappers.@declare_library_product(libkokkoscontainers, "@rpath/libkokkoscontainers.4.3.dylib")
JLLWrappers.@declare_library_product(libkokkoscore, "@rpath/libkokkoscore.4.3.dylib")
JLLWrappers.@declare_library_product(libkokkossimd, "@rpath/libkokkossimd.4.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libkokkoscontainers,
        "lib/libkokkoscontainers.4.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libkokkoscore,
        "lib/libkokkoscore.4.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libkokkossimd,
        "lib/libkokkossimd.4.3.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
